#ifndef DEFAULT_H
#define DEFAULT_H


#define DEFAULT_RF_MODE DSMX
#define STICK_MODE_DEFAULT STICK_MODE2
#define DEFAULT_TX_OPTIONS ((1<<TX_OPTION_FAST_MODEL_SELECT)|(1<<TX_OPTION_CONFIG_WHILE_RUNNIG))
#define DEFAULT_MODEL_TYPE MODEL_TYPE_CLASIC
#define DEFAULT_MODEL_OPTIONS 0

#define EXPO_PERCENT(x) (((x*(CHAN_RANGE*2))+50L)/100)
#define PERCENT(x) (((x*(CHAN_RANGE))+50L)/100)

#define PERCENT_SPECTRUM(x) (((x*(CHAN_RANGE))+62L)/125)

//default trim
#define DEFAULT_TRIM {0,0,0,}

#define DEFAULT_FLIGHT_TIME_HELI (180*50L)/100 //3 minutes at 50% Power
#define DEFAULT_FLIGHT_TIME_AIRPLANE (300*50L)/100 //5 minutes at 50% Power
#define DEFAULT_FLIGHT_TIME_CLASIC (180*50L)/100 //3 minutes at 50% Power


//default rate and expo HELI and e
//ROLL
#define DEFAULT_EXPO_NORM1  CHAN_MIN_VALUE+EXPO_PERCENT(30L)  //30%
#define DEFAULT_EXPO_STUNT1 CHAN_MIN_VALUE+EXPO_PERCENT(30L)  //30%
#define DEFAULT_RATE_NORM1  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(65L) //65%
#define DEFAULT_RATE_STUNT1 CHAN_CENTER_VALUE+PERCENT_SPECTRUM(75L) //75%
//NICK
#define DEFAULT_EXPO_NORM2  CHAN_MIN_VALUE+EXPO_PERCENT(30L)  //30%
#define DEFAULT_EXPO_STUNT2 CHAN_MIN_VALUE+EXPO_PERCENT(30L)  //30%
#define DEFAULT_RATE_NORM2  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(65L) //65%
#define DEFAULT_RATE_STUNT2 CHAN_CENTER_VALUE+PERCENT_SPECTRUM(75L) //75%
//YAW
#define DEFAULT_EXPO_NORM3  CHAN_MIN_VALUE+EXPO_PERCENT(15L)  //15%
#define DEFAULT_EXPO_STUNT3 CHAN_MIN_VALUE+EXPO_PERCENT(15L)  //15%
#define DEFAULT_RATE_NORM3  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(75L) //75%
#define DEFAULT_RATE_STUNT3 CHAN_CENTER_VALUE+PERCENT_SPECTRUM(90L) //90%

//default rate and expo clasic 
#define DEFAULT_EXPO_CLASIC1  CHAN_MIN_VALUE+EXPO_PERCENT(0)  //0%
#define DEFAULT_EXPO_CLASIC2  CHAN_MIN_VALUE+EXPO_PERCENT(0)  //0%
#define DEFAULT_EXPO_CLASIC3  CHAN_MIN_VALUE+EXPO_PERCENT(0)  //0%
#define DEFAULT_RATE_CLASIC1  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(100L) //100%
#define DEFAULT_RATE_CLASIC2  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(100L) //100%
#define DEFAULT_RATE_CLASIC3  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(100L) //100%

//used it initialize STRUCTs
#define DEFAULT_EXPO_X {{DEFAULT_EXPO_NORM1,DEFAULT_EXPO_NORM2,DEFAULT_EXPO_NORM3},{DEFAULT_EXPO_STUNT1,DEFAULT_EXPO_STUNT2,DEFAULT_EXPO_STUNT3}}
#define DEFAULT_RATE_X {{DEFAULT_RATE_NORM1,DEFAULT_RATE_NORM2,DEFAULT_RATE_NORM3},{DEFAULT_RATE_STUNT1,DEFAULT_RATE_STUNT2,DEFAULT_RATE_STUNT3}}
#define DEFAULT_EXPO_CLASSIC {{DEFAULT_EXPO_CLASIC1,DEFAULT_EXPO_CLASIC2,DEFAULT_EXPO_CLASIC3},{DEFAULT_EXPO_CLASIC1,DEFAULT_EXPO_CLASIC2,DEFAULT_EXPO_CLASIC3}}
#define DEFAULT_RATE_CLASSIC {{DEFAULT_RATE_CLASIC1,DEFAULT_RATE_CLASIC2,DEFAULT_RATE_CLASIC3},{DEFAULT_RATE_CLASIC1,DEFAULT_RATE_CLASIC2,DEFAULT_RATE_CLASIC3}}
//Heli
#define DEFAULT_EXPO_HELI DEFAULT_EXPO_X
#define DEFAULT_RATE_HELI DEFAULT_RATE_X
//airplane
#define DEFAULT_EXPO_AIRPLANE DEFAULT_EXPO_X
#define DEFAULT_RATE_AIRPLANE DEFAULT_RATE_X


//default curves for heli
#define DEFAULT_HELI_PITCH_CURVE_NORM1   CHAN_CENTER_VALUE+PERCENT_SPECTRUM(-30L)	//-30%
#define DEFAULT_HELI_PITCH_CURVE_NORM2   CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)		//0%
#define DEFAULT_HELI_PITCH_CURVE_NORM3   CHAN_CENTER_VALUE+PERCENT_SPECTRUM(80L)	//80%
#define DEFAULT_HELI_THR_CURVE_NORM1     CHAN_CENTER_VALUE+PERCENT_SPECTRUM(-100)	//-100%
#define DEFAULT_HELI_THR_CURVE_NORM2	 CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)		//0%
#define DEFAULT_HELI_THR_CURVE_NORM3     CHAN_CENTER_VALUE+PERCENT_SPECTRUM(90L)	//90%
#define DEFAULT_HELI_PITCH_CURVE_STUNT1  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(-90L)	//-90%
#define DEFAULT_HELI_PITCH_CURVE_STUNT2  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)		//0%
#define DEFAULT_HELI_PITCH_CURVE_STUNT3  CHAN_CENTER_VALUE+PERCENT_SPECTRUM(90L)	//90%
#define DEFAULT_HELI_THR_CURVE_STUNT1	 CHAN_CENTER_VALUE+PERCENT_SPECTRUM(90L)	//90%
#define DEFAULT_HELI_THR_CURVE_STUNT2    CHAN_CENTER_VALUE+PERCENT_SPECTRUM(90L)	//90%
#define DEFAULT_HELI_THR_CURVE_STUNT3    CHAN_CENTER_VALUE+PERCENT_SPECTRUM(90L)	//90%
//used it initialize STRUCTs
#define DEFAULT_HELI_THR_CURVE_NORM {DEFAULT_HELI_THR_CURVE_NORM1,DEFAULT_HELI_THR_CURVE_NORM2,DEFAULT_HELI_THR_CURVE_NORM3}
#define DEFAULT_HELI_THR_CURVE_STUNT {DEFAULT_HELI_THR_CURVE_STUNT1,DEFAULT_HELI_THR_CURVE_STUNT2,DEFAULT_HELI_THR_CURVE_STUNT3}
#define DEFAULT_HELI_THR_CURVE {DEFAULT_HELI_THR_CURVE_NORM,DEFAULT_HELI_THR_CURVE_STUNT}
#define DEFAULT_HELI_PITCH_CURVE_NORM {DEFAULT_HELI_PITCH_CURVE_NORM1,DEFAULT_HELI_PITCH_CURVE_NORM2,DEFAULT_HELI_PITCH_CURVE_NORM3}
#define DEFAULT_HELI_PITCH_CURVE_STUNT {DEFAULT_HELI_PITCH_CURVE_STUNT1,DEFAULT_HELI_PITCH_CURVE_STUNT2,DEFAULT_HELI_PITCH_CURVE_STUNT3}
#define DEFAULT_HELI_PITCH_CURVE {DEFAULT_HELI_PITCH_CURVE_NORM,DEFAULT_HELI_PITCH_CURVE_STUNT}	
#define DEFAULT_HELI_CURVES {DEFAULT_HELI_PITCH_CURVE,DEFAULT_HELI_THR_CURVE}


//default mix for airplane
#define DEFAULT_ALIE_MIX1 CHAN_CENTER_VALUE+PERCENT(100L)	//100%
#define DEFAULT_ALIE_MIX2 CHAN_CENTER_VALUE+PERCENT(0)	
#define DEFAULT_ALIE_MIX3 CHAN_CENTER_VALUE+PERCENT(0)
#define DEFAULT_ELEV_MIX1 CHAN_CENTER_VALUE+PERCENT(0)
#define DEFAULT_ELEV_MIX2 CHAN_CENTER_VALUE+PERCENT(100L)	//100%
#define DEFAULT_ELEV_MIX3 CHAN_CENTER_VALUE+PERCENT(0)
#define DEFAULT_AUX_MIX1 CHAN_CENTER_VALUE+PERCENT(-100)	//-100%
#define DEFAULT_AUX_MIX2 CHAN_CENTER_VALUE+PERCENT(0)
#define DEFAULT_AUX_MIX3 CHAN_CENTER_VALUE+PERCENT(0)
//used it initialize STRUCTs
#define DEFAULT_ALIE_MIX_NORM {DEFAULT_ALIE_MIX1,DEFAULT_ALIE_MIX2,DEFAULT_ALIE_MIX3}
#define DEFAULT_ALIE_MIX_STUNT {DEFAULT_ALIE_MIX1,DEFAULT_ALIE_MIX2,DEFAULT_ALIE_MIX3}
#define DEFAULT_ALIE_MIX {DEFAULT_ALIE_MIX_NORM,DEFAULT_ALIE_MIX_STUNT}
#define DEFAULT_ELEV_MIX_NORM {DEFAULT_ELEV_MIX1,DEFAULT_ELEV_MIX2,DEFAULT_ELEV_MIX3}
#define DEFAULT_ELEV_MIX_STUNT {DEFAULT_ELEV_MIX1,DEFAULT_ELEV_MIX2,DEFAULT_ELEV_MIX3}
#define DEFAULT_ELEV_MIX {DEFAULT_ELEV_MIX_NORM,DEFAULT_ELEV_MIX_STUNT}
#define DEFAULT_AUX_MIX_NORM  {DEFAULT_AUX_MIX1,DEFAULT_AUX_MIX2,DEFAULT_AUX_MIX3}
#define DEFAULT_AUX_MIX_STUNT  {DEFAULT_AUX_MIX1,DEFAULT_AUX_MIX2,DEFAULT_AUX_MIX3}
#define DEFAULT_AUX_MIX {DEFAULT_AUX_MIX_NORM,DEFAULT_AUX_MIX_STUNT}
#define DEFAULT_AIRPLANE_MIX {DEFAULT_ALIE_MIX,DEFAULT_ELEV_MIX,DEFAULT_AUX_MIX}	
//gyro gains
	//heli
#define DEFAULT_GYRO_GAIN_HELI_MORM CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)
#define DEFAULT_GYRO_GAIN_HELI_STUNT CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)
#define DEFAULT_GYRO_GAIN_HELI {DEFAULT_GYRO_GAIN_HELI_MORM,DEFAULT_GYRO_GAIN_HELI_STUNT}
	//airplane
#define DEFAULT_GYRO_GAIN_AIRPLANE_NORM CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)
#define DEFAULT_GYRO_GAIN_AIRPLANE_STUNT CHAN_CENTER_VALUE+PERCENT_SPECTRUM(0)
#define DEFAULT_GYRO_GAIN_AIRPLANE {DEFAULT_GYRO_GAIN_AIRPLANE_NORM,DEFAULT_GYRO_GAIN_AIRPLANE_STUNT}
	//clasic
#define DEFAULT_GYRO_GAIN_CLASSIC_NORM CHAN_CENTER_VALUE+PERCENT_SPECTRUM(-100L) 
#define DEFAULT_GYRO_GAIN_CLASSIC_STUNT CHAN_CENTER_VALUE+PERCENT_SPECTRUM(100L)
#define DEFAULT_GYRO_GAIN_CLASSIC {DEFAULT_GYRO_GAIN_CLASSIC_NORM,DEFAULT_GYRO_GAIN_CLASSIC_STUNT}
	
#endif //DEFAULT_H